name:"first action"

on:
  push:
  branches:["main"]


jobs:
  deploy-actions:
    runs-on:ubuntu-latest
    steps:
      uses:
        run:echo "Descargamos un pull del codigo"
        run:echo "Correr migraciones"
        run:echo "Generar binario"
        run:echo "Publicar version"
